import { FormEvent, useState } from 'react'
import { BarChart3, CalendarCheck, ChevronDown, Eye, EyeOff, LayoutDashboard, LogOut, Plus, Search, Settings, UserPlus, Users } from 'lucide-react'
import { supabase } from './lib/supabase'

type View = 'dashboard' | 'attendees' | 'register' | 'checkin'
const attendees = [
  ['Amelia Thornton', 'AT', 'amelia.thornton@arc.com', '+1 202 555 0142', 'Today, 09:42'],
  ['Daniel Cooper', 'DC', 'daniel.cooper@north.co', '+1 202 555 0168', 'Today, 09:25'],
  ['Olivia Bennett', 'OB', 'olivia.bennett@alton.com', '+1 202 555 0190', '23 Aug, 16:30'],
  ['Marcus Ellison', 'ME', 'marcus.ellison@novus.com', '+1 202 555 0114', '—'],
] as const

function App() {
  const [authenticated, setAuthenticated] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [view, setView] = useState<View>('dashboard')
  const [query, setQuery] = useState('')
  const [message, setMessage] = useState('')
  const flash = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(''), 2600) }
  async function signIn(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    if (supabase) { const { error } = await supabase.auth.signInWithPassword({ email: String(data.get('email')), password: String(data.get('password')) }); if (error) return flash(error.message) }
    setAuthenticated(true)
  }
  if (!authenticated) return <Login signIn={signIn} showPassword={showPassword} setShowPassword={setShowPassword} />
  return <div className="shell"><Sidebar view={view} onView={setView} onLogout={() => setAuthenticated(false)} /><main><header><div><span className="eyebrow">{view === 'dashboard' ? 'OVERVIEW' : 'MANAGEMENT'}</span><h1>{view === 'dashboard' ? 'Dashboard' : view === 'checkin' ? 'Daily check-in' : view === 'register' ? 'Register attendee' : 'All attendees'}</h1></div><div className="profile"><div className="avatar gold">KM</div><div><b>Karim M.</b><small>Administrator</small></div><ChevronDown size={15}/></div></header>{view === 'dashboard' && <Dashboard onView={setView}/>} {view === 'attendees' && <Attendees onView={setView}/>} {view === 'checkin' && <Checkin query={query} setQuery={setQuery} flash={flash}/>} {view === 'register' && <Register onSave={() => { flash('Attendee profile saved successfully'); setView('attendees') }}/>}</main>{message && <div className="toast">✓ {message}</div>}</div>
}

function Login({ signIn, showPassword, setShowPassword }: { signIn: (e: FormEvent<HTMLFormElement>) => void; showPassword: boolean; setShowPassword: (v: boolean) => void }) { return <div className="login"><section className="hero"><div className="login-brand"><span>A</span>AttendanceHub <em>PRO</em></div><div><p className="eyebrow">ATTENDANCE, ELEVATED</p><h1>Your people.<br/>Your standard.</h1><p>Professional attendance management, beautifully made for modern organisations.</p></div></section><section className="login-panel"><form className="login-card" onSubmit={signIn}><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your workspace</h2><p>Enter your credentials to continue.</p><label>Email address<input name="email" type="email" placeholder="name@company.com" required/></label><label>Password<div className="password"><input name="password" type={showPassword ? 'text' : 'password'} placeholder="Enter your password" required/><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={15}/> : <Eye size={15}/>}</button></div></label><div className="login-options"><label><input type="checkbox"/> Remember me</label><a>Forgot password?</a></div><button className="primary wide">Sign in to AttendanceHub <b>→</b></button><small className="secure">✦ Secured by AttendanceHub Pro</small></form></section></div> }
function Sidebar({ view, onView, onLogout }: { view: View; onView: (v: View) => void; onLogout: () => void }) { const Item=({id,icon:Icon,label}:{id:View,icon:typeof Users,label:string})=><button className={view===id?'active':''} onClick={()=>onView(id)}><Icon size={17}/>{label}</button>; return <aside><div className="brand"><span>A</span>AttendanceHub<em>PRO</em></div><div className="workspace">◇ <div><small>WORKSPACE</small><b>Grand Meridian</b></div><ChevronDown size={14}/></div><nav><p>MAIN MENU</p><Item id="dashboard" icon={LayoutDashboard} label="Dashboard"/><p>MANAGEMENT</p><Item id="attendees" icon={Users} label="Attendees"/><button onClick={()=>onView('register')}><UserPlus size={17}/> Register attendee</button><Item id="checkin" icon={CalendarCheck} label="Daily check-in"/><p>REPORTING</p><button><BarChart3 size={17}/> Reports</button><p>ACCOUNT</p><button><Settings size={17}/> Settings</button></nav><button className="logout" onClick={onLogout}><LogOut size={16}/> Log out</button></aside> }
function Dashboard({onView}:{onView:(v:View)=>void}) { return <section><div className="welcome"><div><h2>Good morning, Karim <span>✦</span></h2><p>Here’s what’s happening at Grand Meridian today.</p></div><div className="date">◷ <div><small>MONDAY</small><b>24 August, 2026</b></div></div></div><div className="metrics">{[['TOTAL ATTENDEES','12,486','↑ 12.5%'],["TODAY'S ATTENDANCE",'1,284','↑ 8.2%'],['WEEKLY ATTENDANCE','6,892','↑ 4.8%'],['ATTENDANCE RATE','92.6%','↑ 2.1%']].map(([label,value,change],i)=><article className="metric" key={label}><div className={'metric-icon i'+i}>{i===0?'♙':i===1?'✓':i===2?'◫':'◉'}</div><small>{label}</small><strong>{value}</strong><p>{change} <span>vs. last month</span></p></article>)}</div><div className="dashboard-grid"><article className="card chart-card"><div className="card-title"><div><h3>Attendance overview</h3><p>Attendance activity across the current week</p></div><span>● Present　○ Absent</span></div><div className="chart"><svg viewBox="0 0 620 180" preserveAspectRatio="none"><defs><linearGradient id="goldFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#d9a86c" stopOpacity=".32"/><stop offset="1" stopColor="#d9a86c" stopOpacity="0"/></linearGradient></defs><path className="grid" d="M0 20H620M0 75H620M0 130H620M0 178H620"/><path fill="url(#goldFill)" d="M0 130C35 110 55 113 88 95S144 107 176 79 231 74 266 91 321 51 356 59 409 27 444 50 498 59 531 34 586 56 620 18V180H0Z"/><path className="curve" d="M0 130C35 110 55 113 88 95S144 107 176 79 231 74 266 91 321 51 356 59 409 27 444 50 498 59 531 34 586 56 620 18"/></svg><div><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></article><article className="card quick"><h3>Quick actions</h3><p>Get things done faster</p><button className="primary" onClick={()=>onView('checkin')}>＋ <span>Check in attendee<small>Register today’s attendance</small></span> →</button><button onClick={()=>onView('register')}>♙ <span>Register attendee<small>Add a new profile</small></span> →</button><button>◫ <span>View reports<small>Explore attendance insights</small></span> →</button></article></div><AttendeeTable short /></section> }
function AttendeeTable({short=false}:{short?:boolean}) { return <article className="card attendees-table"><div className="card-title"><div><h3>{short?'Recent attendees':'Attendee directory'}</h3><p>{short?'Latest people added to your workspace':'Manage your registered attendee profiles'}</p></div></div><div className="scroll"><table><thead><tr><th>ATTENDEE</th><th>CONTACT</th><th>REGISTERED</th><th>LAST ATTENDANCE</th><th>STATUS</th></tr></thead><tbody>{attendees.map(a=><tr key={a[0]}><td><div className="person"><div className="avatar">{a[1]}</div><div>{a[0]}<small>{a[2]}</small></div></div></td><td>{a[3]}</td><td>24 Aug 2026</td><td>{a[4]}</td><td><span className="status">Active</span></td></tr>)}</tbody></table></div></article> }
function Attendees({onView}:{onView:(v:View)=>void}) { return <section><div className="welcome"><div><h2>All attendees</h2><p>Manage your registered attendee directory.</p></div><button className="primary" onClick={()=>onView('register')}><Plus size={15}/> Register attendee</button></div><div className="search"><Search size={16}/><input placeholder="Search attendees by name, email or phone"/></div><AttendeeTable /></section> }
function Checkin({query,setQuery,flash}:{query:string,setQuery:(x:string)=>void,flash:(x:string)=>void}) { const results=attendees.filter(a=>a.join(' ').toLowerCase().includes(query.toLowerCase())); return <section><div className="welcome"><div><h2>Daily check-in</h2><p>Find an attendee and record their arrival in a moment.</p></div></div><div className="checkin-grid"><article className="card checkin"><label>SEARCH ATTENDEES</label><div className="search"><Search size={16}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, email or phone number"/></div>{query && results.map(a=><div className="result" key={a[0]}><div className="avatar">{a[1]}</div><div><b>{a[0]}</b><small>{a[2]} · {a[3]}</small></div><button className="primary" onClick={()=>flash(`${a[0]} checked in successfully`)}>Check in</button></div>)}</article><article className="card activity"><h3>Today’s activity</h3><strong>1,284</strong><p>people checked in today</p><div className="progress"><i/></div><small>92.6% of expected attendees</small></article></div></section> }
function Register({onSave}:{onSave:()=>void}) { return <section><div className="welcome"><div><h2>Register attendee</h2><p>Create a new attendee profile for your workspace.</p></div></div><form className="card form" onSubmit={e=>{e.preventDefault();onSave()}}><div className="photo"><div className="avatar">♙</div><div><h3>Profile photo</h3><p>PNG or JPG, up to 5MB</p></div><button type="button">Upload photo</button></div><div className="fields">{['Full name','Email address','Phone number','Gender','Date of birth','National ID number','Organization / Company','Department','Position','Country','City','Address'].map((x,i)=><label key={x}>{x}{x==='Gender'?<select><option>Select gender</option><option>Female</option><option>Male</option></select>:<input required={i<2} type={x==='Date of birth'?'date':x==='Email address'?'email':'text'} placeholder={`Enter ${x.toLowerCase()}`}/>}</label>)}<label className="full">Notes<textarea placeholder="Add an internal note about this attendee..."/></label></div><div className="form-actions"><button type="button">Cancel</button><button className="primary">Save attendee</button></div></form></section> }
export default App
